---
title: "Empirical Project 1"
author: "Feven Yohannes"
date: "February 19, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Needed Packages

if (!require(tidyverse)) install.packages("tidyverse"); library(tidyverse)
if (!require(haven)) install.packages("haven"); library(haven)
if (!require(ggplot2)) install.packages("ggplot2"); library(ggplot2)
if (!require(statar)) install.packages("statar"); library(statar)
library(dplyr)
library(gt)
library(readr)
library(tidyr)
library(cowplot)

```


```{r}

# Downloading the Data 

atlas <- read_dta("atlas.dta")


# Subsetting the Data for State and City

MA <- subset(atlas,state == 25)

boston <- subset(atlas,state == 25 & county == 25)


# Subsetting for my tracts (last 6 digits of the tract name on opportunity atlas)

Harrison_Lenox <- boston %>%
  filter(tract == 071101)

Shawmut <- boston %>%
  filter(tract == 070500)

Columbus_Ave <- boston %>%
  filter(tract == 070800)

Prudential <- boston %>%
  filter(tract == 010600)


```


```{r, Tract Statistics}

# Racial shares at Harrison Lenox --- 45 percent, Black Share 26 percent 

Harrison_Lenox %>%
  select(share_white2000)

Harrison_Lenox %>%
  select(share_black2000)

# Racial Shares at Shawmut Ave --- 47 percent, Black Share 9 percent 

Shawmut %>%
  select(share_white2000)

Shawmut %>%
  select(share_black2000)


  
```


```{r, Making Graph 1}

# Making a bar chart for Average White Incomes

# I need to rename tract values 


graph1 <- boston %>%
  
  # Made tract a character variable so I could have a better x axis on the graph 
  
  mutate(tract= as.character(tract)) %>%
  filter(tract %in% c(071101,070500)) %>%
  # rename.values("071101"="Harrison_Lenox") %>%
  ggplot(aes(x=tract, y=kfr_white_pooled_p25)) + geom_col(fill="skyblue2") +
  labs(x="Tract", 
       y= "Average Income Percentile",
       title = "Upward Mobility for White Children")


# Making a bar chart for Average Black Incomes

graph2 <- boston %>%
  filter(tract %in% c(071101,070500)) %>%
  mutate(tract= as.character(tract)) %>%
  ggplot(aes(x=tract, y=kfr_black_pooled_p25)) + geom_col(fill="violetred") +
  labs(x="Tract", 
       y= "Average Income Percentile",
       title= "Upward Mobility for Black Children")

# Merge the plots together and save it to ggsave

plot_grid(graph1,graph2)  +
  theme(plot.title = element_text(face = "bold",size=30))+
  theme(plot.subtitle = element_text(face = "bold",size=29)) +
  theme(plot.caption =element_text(face = "bold",size=27))+
    theme(axis.title.x = element_text(size = 30),
          axis.title.y = element_text(size = 30)) +
    theme(
  legend.title = element_text(color = "black", size = 29),
  legend.text = element_text(color = "black", size = 29)
  ) +
    theme(axis.text.x = element_text(color = "black", size = 26, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 26, angle = 0, hjust = 1, vjust = 0, face = "plain")) 
  
  
  ggsave("figure4.png", height = 13, width = 21)


```


```{r, Boston Graph}

# Making a graph of distribution of incomes in Boston

boston %>%
  ggplot(aes(x=hhinc_mean2000)) + geom_histogram(color="black", fill="white") +
  geom_vline(aes(xintercept= mean(hhinc_mean2000)),color="blue") +
  labs(x= "Average Income",
       y= "Number of Tracts",
       title= "Investigating the Average Income in Boston Households in 2000",
       subtitle= "Average Income in Boston is around 77,000 dollars") +
  theme(plot.title = element_text(face = "bold",size=30))+
  theme(plot.subtitle = element_text(face = "bold",size=29)) +
    theme(axis.title.x = element_text(size = 30),
          axis.title.y = element_text(size = 30)) +
    theme(
  legend.title = element_text(color = "black", size = 29),
  legend.text = element_text(color = "black", size = 29)
  ) +
    theme(axis.text.x = element_text(color = "black", size = 26, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 26, angle = 0, hjust = 1, vjust = 0, face = "plain")) 
  
  
  ggsave("figure3.png", height = 13, width = 21)
  


```





```{r, Caclulating Some Statistics}

# Average percentile for the counties in Boston for the bottom 25 percentile is 43.2 percent

boston %>%
# Filter out NA's 
  drop_na(kfr_pooled_pooled_p25) %>%
  summarise(avg=mean(kfr_pooled_pooled_p25))


# Average percentile for the counties in Boston for the bottom 25 percentile BLACK CHILDREN is 38.14 percent 

boston %>%
# Filter out NA's 
  drop_na(kfr_black_pooled_p25) %>%
  summarise(avg=mean(kfr_black_pooled_p25))

# Average percentile for the counties in Boston for the bottom 25 percentile WHITE CHILDREN is 49.69 percent

boston %>%
# Filter out NA's 
  drop_na(kfr_white_pooled_p25) %>%
  summarise(avg=mean(kfr_white_pooled_p25))



```


```{r, Calculating More Statisitcs}

# Calculating More Statisitcs Part 2

# National Data

summary(atlas$kfr_pooled_pooled_p25)
mean(atlas$kfr_pooled_pooled_p25, na.rm=TRUE)
sd(atlas$kfr_pooled_pooled_p25, na.rm=TRUE)


# State Level Data

summary(MA$kfr_pooled_pooled_p25)
mean(MA$kfr_pooled_pooled_p25, na.rm=TRUE)
sd(MA$kfr_pooled_pooled_p25, na.rm=TRUE)

# Boston Data

summary(boston$kfr_pooled_pooled_p25)
mean(boston$kfr_pooled_pooled_p25, na.rm=TRUE)
sd(boston$kfr_pooled_pooled_p25, na.rm=TRUE)
```

```{r, Regressions}

#Making Regressions for the entire city of Boston 

model1 <- lm(kfr_pooled_pooled_p25 ~  frac_coll_plus2000 + emp2000 +jail_pooled_pooled_p25, data= boston)

# Summary of data

summary(model1)


# Making Regressions for White Children in Boston 

model_white <- lm(kfr_white_pooled_p25 ~  frac_coll_plus2000 + emp2000 +jail_pooled_pooled_p25, data= boston)

# Summary of data

summary(model_white)


# Making Regressions for Black Children in Boston 

model_black <- lm(kfr_black_pooled_p25 ~  frac_coll_plus2000 + emp2000 +jail_pooled_pooled_p25, data= boston)

# Summary of data

summary(model_black)

```
```{r, Making Correlation Graphs--- Prison}


# Creating Correlation Graphs for Percentatge Jailed and Mean Income 

boston %>%
  filter(jail_pooled_pooled_p25 >0) %>%
  ggplot(aes(x=jail_pooled_pooled_p25,y=kfr_pooled_pooled_p25)) +geom_point() + geom_smooth(method="lm") +
  labs(x= "Percentage of Individuals Imprisoned for Families at the 25th Percentile",
       y= "Adult Income Ranking for Children at the 25th Percentile",
       title= "Investigating the Relationship between Incarceration Rates and Average Income in Boston",
       subtitle= "Negative Relationship between Incarceration Rates and Upward Mobility") +
  theme(plot.title = element_text(face = "bold",size=30))+
  theme(plot.subtitle = element_text(face = "bold",size=29)) +
  theme(plot.caption =element_text(face = "bold",size=27))+
    theme(axis.title.x = element_text(size = 30),
          axis.title.y = element_text(size = 30)) +
    theme(
  legend.title = element_text(color = "black", size = 29),
  legend.text = element_text(color = "black", size = 29)
  ) +
    theme(axis.text.x = element_text(color = "black", size = 26, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 26, angle = 0, hjust = 1, vjust = 0, face = "plain")) 
  
  
  ggsave("figure8.png", height = 13, width = 21)

# How can we get negative jail pooled values

boston %>%
  select(jail_pooled_pooled_p25)


# Looking at the Co-Variate of these two variables-- Avergae for Boston -- Correlation is -0.1769983

cor(boston$kfr_pooled_pooled_p25, boston$jail_pooled_pooled_p25, use="pairwise.complete.obs")


# Co- Variate for White Children Only--- Correlation is -0.1432262


cor(boston$kfr_white_pooled_p25, boston$jail_white_pooled_p25, use="pairwise.complete.obs")


# Co- Variate for Black Children Only--- Correlation is -0.2620763


cor(boston$kfr_black_pooled_p25 ,boston$jail_black_pooled_p25, use="pairwise.complete.obs")




```

```{r, Making Correlation Graphs, College Education}

boston %>%
  ggplot(aes(x=frac_coll_plus2000,y=kfr_pooled_pooled_p25)) +geom_point() +geom_smooth(method="lm") +
  labs(x= "Percentage of Individuals With a College Degree in 2000 for Families at the 25th Percentile",
       y= "Adult Income Ranking for Children at the 25th Percentile",
       title= "Investigating the Relationship between Higher Education Rates Rates and Average Income in Boston",
       subtitle= "Positive Relationship between HigherEducation  Rates and Upward Mobility")


# Looking at the Co-Variate of mean income and education -- Avergae for Boston -- Correlation is 0.3119923

cor(boston$kfr_pooled_pooled_p25, boston$frac_coll_plus2000, use="pairwise.complete.obs")


# Co- Variate for White Children Only--- Correlation is 0.3949435


cor(boston$kfr_white_pooled_p25, boston$frac_coll_plus2000, use="pairwise.complete.obs")


# Co- Variate for Black Children Only--- Correlation is  -0.1587245
    # Why is this Negative


cor(boston$kfr_black_pooled_p25,boston$frac_coll_plus2000, use="pairwise.complete.obs")




```



```{r, Employment Rates}

# Investigating employment rates

# Creating the graph 

boston %>%
  ggplot(aes(x=emp2000,y=kfr_pooled_pooled_p25)) +geom_point() +geom_smooth(method="lm") +
  labs(x= "Employment Rates in 2000 for Families at the 25th Percentile",
       y= "Adult Income Ranking for Children at the 25th Percentile",
       title= "Investigating the Relationship between Employment Rates and Average Income in Boston",
       subtitle= "Positive Relationship between Employment Rates and Upward Mobility")+
  theme(plot.title = element_text(face = "bold",size=30))+
  theme(plot.subtitle = element_text(face = "bold",size=29)) +
  theme(plot.caption =element_text(face = "bold",size=27))+
    theme(axis.title.x = element_text(size = 30),
          axis.title.y = element_text(size = 30)) +
    theme(
  legend.title = element_text(color = "black", size = 29),
  legend.text = element_text(color = "black", size = 29)
  ) +
    theme(axis.text.x = element_text(color = "black", size = 26, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 26, angle = 0, hjust = 1, vjust = 0, face = "plain")) 
  
  
  ggsave("figure7.png", height = 13, width = 21)


# Calculating the co-variate

cor(boston$kfr_black_pooled_p25, boston$emp2000, use="pairwise.complete.obs")


Shawmut %>%
  select(job_density_2013)

Harrison_Lenox  %>%
  select(job_density_2013)


# Creating a new data frame 

tract <- c("Harrison Lenox", "Harrison Lenox", "Shawmut Ave","Shawmut Ave")
employment_rates  <- c(89,73,72,71)
race <- c("White Children","Black Children","Black Children","White Children")

employment_df <- data.frame(tract,employment_rates,race)



# Making a Graph of Employment rates between Tracts

employment_df %>%
  ggplot(aes(x=tract,y=employment_rates)) + geom_col(fill="plum4") +facet_wrap(~race) +
  labs(x= "Tract",
       y= "Employment Rates",
       title= "Investigating the Relationship between Employment Rates and Average Income") +
  theme(plot.title = element_text(face = "bold",size=30))+
  theme(plot.subtitle = element_text(face = "bold",size=29)) +
  theme(plot.caption =element_text(face = "bold",size=27))+
    theme(axis.title.x = element_text(size = 30),
          axis.title.y = element_text(size = 30)) +
    theme(
  legend.title = element_text(color = "black", size = 29),
  legend.text = element_text(color = "black", size = 29)
  ) +
    theme(axis.text.x = element_text(color = "black", size = 26, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 26, angle = 0, hjust = 1, vjust = 0, face = "plain")) 
  
  
  ggsave("figure6.png", height = 13, width = 21)


```


```{r, Single Parents}

# Investigating Single Parent Shares

# Creating the Graph for Single Parents and Income Outcome

boston %>%
  ggplot(aes(x=singleparent_share2000,y=kfr_pooled_pooled_p25)) +geom_point() + geom_smooth(method="lm") +
  labs(x= "Share of Single-Headed Households with Children in 2000",
       y= "Adult Income Ranking for Children at the 25th Percentile",
       title= "Investigating the Relationship between Single Parent Rates Rates Rates and Average Income in Boston",
       subtitle= "Negative Relationship between Single Parent Rates and Upward Mobility") +
  theme(plot.title = element_text(face = "bold",size=30))+
  theme(plot.subtitle = element_text(face = "bold",size=29)) +
  theme(plot.caption =element_text(face = "bold",size=27))+
    theme(axis.title.x = element_text(size = 30),
          axis.title.y = element_text(size = 30)) +
    theme(
  legend.title = element_text(color = "black", size = 29),
  legend.text = element_text(color = "black", size = 29)
  ) +
    theme(axis.text.x = element_text(color = "black", size = 26, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 26, angle = 0, hjust = 1, vjust = 0, face = "plain")) 
  
  
  ggsave("figure5.png", height = 13, width = 21)
```


#Looking at the single parent household rates from 1990


Shawmut %>%
  select(singleparent_share2000) # 0.5668449 0.5435898(2000)

# Harrison Ave single parent households are # 0.5629139--- 0.6530612(2000)


# Calculating the co-variate

cor(boston$kfr_pooled_pooled_p25, boston$singleparent_share2000, use="pairwise.complete.obs")




```{r, Graph for Incarceration Rates}

black_incarceration <- boston %>%
  filter(tract %in% c(071101,070500)) %>%
  mutate(tract= as.character(tract)) %>%
  ggplot(aes(x=tract,y=jail_black_pooled_p25)) +geom_col(fill="red4")  +
  labs(x="Tract", 
       y= "Percentage of Black Individauls Incarcerated",
       title = "Incarceration Rates for Black Individuals in Harrison Lenox and Shawmut Ave",
       caption = "071101= Harrison Lenox , 070500 = Shawmut Ave")

boston %>%
  filter(tract %in% c(071101,070500)) %>%
  mutate(tract= as.character(tract)) %>%
  ggplot(aes(x=tract,y=jail_white_pooled_p25)) +geom_col(fill="orange3")  +
  labs(x="Tract", 
       y= "Percentage of White Individauls Incarcerated",
       title = "Incarceration Rates for Black Individuals in Harrison Lenox and Shawmut Ave",
       caption = "071101= Harrison Lenox , 070500 = Shawmut Ave")



# Creating a new data frame for Incarceration Rates 

tract <- c("Harrison Lenox", "Harrison Lenox", "Shawmut Ave","Shawmut Ave")
employment_rates  <- c(1,6.9,1,1)
race <- c("White Children","Black Children","Black Children","White Children")

incarceration_df <- data.frame(tract,employment_rates,race)



# Making a Graph 

incarceration_df %>%
  ggplot(aes(x=tract,y=employment_rates)) + geom_col(fill="brown4") +facet_wrap(~race) +
  labs(x= "Tract",
       y= "Incarceration Rates",
       title= "Investigating the Relationship between Incarceration Rates and Average Income",
       caption = "1 percent Incarceration Rates actually show less than 1 percent Incarceration Rates") +
  theme(plot.title = element_text(face = "bold",size=30))+
  theme(plot.subtitle = element_text(face = "bold",size=29)) +
  theme(plot.caption =element_text(face = "bold",size=27))+
    theme(axis.title.x = element_text(size = 30),
          axis.title.y = element_text(size = 30)) +
    theme(
  legend.title = element_text(color = "black", size = 29),
  legend.text = element_text(color = "black", size = 29)
  ) +
    theme(axis.text.x = element_text(color = "black", size = 26, hjust = .5, vjust = .5, face = "plain"),
        axis.text.y = element_text(color = "black", size = 26, angle = 0, hjust = 1, vjust = 0, face = "plain")) 
  
  
  ggsave("figure9.png", height = 13, width = 21)


```

